In [2]:
import numpy as np
from scipy import linalg

In [3]:
def value_function(π, P, r, gamma=0.9):
    print('---- P ----  --- r ---')
    print(P,r)
    I = np.eye(P.shape[0])
    V = np.dot(linalg.inv((I - gamma*P)), r)
    print(f'Policy π_{π}, value function:')
    return(V)

In [4]:
value_function(π='1', P = np.array([[0.9,0.1],[0.9,0.1]]), r = np.array([6,-2.1]))

---- P ----  --- r ---
[[0.9 0.1]
 [0.9 0.1]] [ 6.  -2.1]
Policy π_1, value function:


array([52.71, 44.61])

In [6]:
value_function(π='2', P = np.array([[0.9,0.1],[0,1]]), r = np.array([6,1]))

---- P ----  --- r ---
[[0.9 0.1]
 [0.  1. ]] [6 1]
Policy π_2, value function:


array([36.31578947, 10.        ])

In [7]:
value_function(π='3', P = np.array([[0.9,0.1],[1,0]]), r = np.array([6,0]))

---- P ----  --- r ---
[[0.9 0.1]
 [1.  0. ]] [6 0]
Policy π_3, value function:


array([55.04587156, 49.5412844 ])

In [11]:
value_function(π='4', P = np.array([[1,0],[0.9,0.1]]), r = np.array([1,-2.1]))

---- P ----  --- r ---
[[1.  0. ]
 [0.9 0.1]] [ 1.  -2.1]
Policy π_4, value function:


array([10.        ,  6.59340659])

In [9]:
value_function(π='5', P = np.array([[1,0],[0,1]]), r = np.array([1,1]))

---- P ----  --- r ---
[[1 0]
 [0 1]] [1 1]
Policy π_5, value function:


array([10., 10.])

In [10]:
value_function(π='6', P = np.array([[1,0],[1,0]]), r = np.array([1,0]))

---- P ----  --- r ---
[[1 0]
 [1 0]] [1 0]
Policy π_6, value function:


array([10.,  9.])